# Generated by Django 5.1.4 on 2025-12-05 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
